spring:
  application:
    name: bookapi-microservice

server:
  port: 9997

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
hystrix:
  command:
    getBookBasicInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  
    getBookRating:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000  

logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'