spring:
  application:
    name: bookinfo-microservice

server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
bookService:
  getBookBasicInfo:
    delay: 200
  getBookRating:
    delay: 200
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'
